[package]
name = "serialport5"
version = "5.0.0"
authors = ["thewh1teagle"]
categories = ["hardware-support"]
edition = "2018"
keywords = ["serial", "hardware", "system", "RS232"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://gitlab.com/susurrus/serialport-rs"
description = "A cross-platform low-level serial port library"
documentation = "https://docs.rs/serialport/*/serialport"

[badges]
maintenance = { status = "looking-for-maintainer" }
appveyor = { repository = "Susurrus/serialport-rs", service = "gitlab" }
gitlab = { repository = "susurrus/serialport-rs" }
travis-ci = { repository = "Susurrus/serialport-rs" }

[features]
default = ["libudev"]

[dev-dependencies]
clap = "3.0.14"

[target."cfg(unix)".dependencies]
nix = "0.23.1"
bitflags = "1.3.2"
cfg-if = "1.0"

[target.'cfg(all(target_os = "linux", not(target_env = "musl")))'.dependencies]
libudev = { version = "0.3.0", optional = true }

[target."cfg(windows)".dependencies]
regex = "1.5.4"

[target."cfg(windows)".dependencies.winapi]
version = "0.3.9"
features = ["cguid", "commapi", "errhandlingapi", "fileapi", "guiddef", "handleapi", "minwinbase",
            "minwindef", "ntdef", "setupapi", "winbase", "winerror", "winnt", "ioapiset", "synchapi"]

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
IOKit-sys = "0.1.5"
mach = "0.3.2"
CoreFoundation-sys = "0.1.3"
